import "./globals.css";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "owl.carousel/dist/assets/owl.carousel.css";
import "owl.carousel/dist/assets/owl.theme.default.css";
import Head from "next/head";
import "./Home.css";
import Script from "next/script";
import Header from "@/Components/Header/Header";
import Footer from "@/Components/Footer/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
          crossorigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Barlow:wght@300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
          type="text/css"
        ></link>
      </Head>
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
        <Script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></Script>
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></Script>
        <Script src="https://cdn.jsdelivr.net/npm/react/umd/react.production.min.js"></Script>
        <Script src="https://cdn.jsdelivr.net/npm/react-dom/umd/react-dom.production.min.js"></Script>
        <Script src="https://cdn.jsdelivr.net/npm/react-bootstrap@next/dist/react-bootstrap.min.js"></Script>
        <Script src="https://unpkg.com/react-bootstrap@next/dist/react-bootstrap.min.js"></Script>
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"></Script>
        <Script
          type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/jquery.sticky/1.0.4/jquery.sticky.js"
        ></Script>
        <Script
          type="text/javascript"
          src="https://preview.colorlib.com/theme/bootstrap/website-menu-07/js/main.js"
        ></Script>
      </body>
    </html>
  );
}
